### ISSUE TITLE
Implement selection and related methods

### ISSUE THREAD

**Issue by dblodgett-usgs** [keller-mark/pizzarr#104]
There are lots of todos in the selection methods of the zarr array class.

https://github.com/keller-mark/pizzarr/blob/efe90f760296fedf737d8dd8d12157d8bd579fb9/R/zarr-array.R#L1093

Related to #97

**Comment by Artur-man** [comment]
I have started here, will let you know how it goes: 

https://github.com/Artur-man/pizzarr/blob/145a93283053ac9eedeca5a56d98fdd083a82c7a/R/indexing.R#L353-L371
