### ISSUE TITLE
Different behavior when running get in parallel.

### ISSUE THREAD

**Issue by dblodgett-usgs** [keller-mark/pizzarr#115]
**Describe the bug**
Getting an error when operating in parallel that I don't see when not parallel. 

This is only reproducible when things have been altered in the parallel read option. 

**To Reproduce**
``` r
library(pizzarr)

options(pizzarr.parallel_read_enabled = 2)

url <- "https://usgs.osn.mghpcc.org/mdmf/gdp/stageiv_combined.zarr/"

z <- zarr_open(url)

dim(z$get_item("latitude")$as.array())
#> [1]  881 1121

options(pizzarr.parallel_read_enabled = "future")
future::plan(future::multisession, workers = 8)

dim(z$get_item("longitude")$as.array())
#> Loading required namespace: future.apply
#> Warning: UNRELIABLE VALUE: One of the 'future.apply' iterations
#> ('future_lapply-1') unexpectedly generated random numbers without declaring so.
#> There is a risk that those random numbers are not statistically sound and the
#> overall results might be invalid. To fix this, specify 'future.seed=TRUE'. This
#> ensures that proper, parallel-safe random numbers are produced via the
#> L'Ecuyer-CMRG method. To disable this check, use 'future.seed = NULL', or set
#> option 'future.rng.onMisuse' to "ignore".
#> [1] "\"decompress_chunk_BLOSC\" not available for .Call() for package \"Rarr\""
#> Error in private$chunk_getitem_part2(part1_result, proj$chunk_coords, : Different type of error - rethrow
```

<sup>Created on 2024-11-19 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Expected behavior**
I would expect these two to be identical.

**Comment by dblodgett-usgs** [comment]
In good news, I pulled down the latest changes and this was already fixed!

**Comment by dblodgett-usgs** [comment]
Still happening with future parallel option.

**Comment by keller-mark** [comment]
Perhaps related to this? https://stackoverflow.com/q/38518387 although I am not sure from the stackoverflow post how exactly to resolve

**Comment by keller-mark** [comment]
Maybe the `packages` argument of future needs to be passed in to specify that Rcpp functions from Rarr should be made available in the parallel processes https://future.futureverse.org/reference/future.html

**Comment by dblodgett-usgs** [comment]
I've been looking into this and can get passed the first issue but am now getting:

`<simpleError in curl::handle_setopt(opts$url$handle, .list = opts$options): handle is dead>`

From here: https://github.com/keller-mark/pizzarr/blob/67359ddc9ec934531a397b207b03e5817cc95345/R/zarr-array.R#L531

This seems to be some issue with httr2 objects not being portable between R sessions :/

**Comment by keller-mark** [comment]
Weird, I had added a comment here about a parallel issue but thought it had been solved https://github.com/keller-mark/pizzarr/blob/67359ddc9ec934531a397b207b03e5817cc95345/R/stores.R#L376

**Comment by dblodgett-usgs** [comment]
OK -- so lots of unreproducible issues cropped up along the way, but I did get this figured out. Will PR a small patch PR rather than piling on to the open one.

**Comment by dblodgett-usgs** [comment]
hmmmm... actually, I am going to merge this into my open PR. There's a commit in there for supporting cluster objects in windows that I need to get testing to work.
