### ISSUE TITLE
Linux parallel vignette

### ISSUE THREAD

**Issue by dblodgett-usgs** [keller-mark/pizzarr#117]
**Describe the bug**
The vignette for parallel operation is failing the linux github actions and I don't have a linux environment to debug it. 

Do we have a linux person who could try and figure out what's up or should I spin up a container to try and figure it out?

There is some github actions ssh portal thing I could try to use too, but it's been a while and maynbe someone else could just try it out on their local environment?

**Comment by keller-mark** [comment]
I saw that as well. I am not experiencing it on macOS either locally

**Comment by dblodgett-usgs** [comment]
Well, that's annoying, I just got a linux environment working with it and it worked fine. More debugging tomorrow.

**Comment by dblodgett-usgs** [comment]
Should be fixed in #118
