### ISSUE TITLE
More tests for compatibility with zarr-python implementation

### ISSUE THREAD

**Issue by keller-mark** [keller-mark/pizzarr#18]
- [x] We should test that stores/arrays/groups written by zarr-python are read-able by pizzarr.
- [x] We should test that stores/arrays/groups written by pizzarr are read-able by zarr-python.

**Comment by dblodgett-usgs** [comment]
I just did:

```r
library(pizzarr)

dir <- "./tests/testthat/test_data/write_test.zarr"

z <- DirectoryStore$new(dir)

a <- volcano

za <- zarr_create(dim(volcano), store = z, overwrite = TRUE)

za$set_item("...", a)
```

With that file, I can do:

```python
import zarr

zarr.open_array("write_test.zarr")

# <zarr.core.Array (87, 61) float64>
```

This test identified the bug with unboxing json that's fixed in #85 

What other aspects of pizzarr output should we be testing you think?

**Comment by dblodgett-usgs** [comment]
Think we can call this done @keller-mark  ?

**Comment by keller-mark** [comment]
Yes that sounds good
