### ISSUE TITLE
Add tests with ":" indexing

### ISSUE THREAD

**Issue by keller-mark** [keller-mark/pizzarr#40]

**Comment by dblodgett-usgs** [comment]
I just implemented a test that I think addresses this -- but I'm not sure I know exactly what you mean by ":" indexing.

Is this what you are getting at?

```r
test_that("Zarr Array can be accessed with ", {
  g <- zarr_volcano()
  
  a <- g$get_item("volcano")
  
  sub <- a[1:10,1]
  
  expect_equal(class(sub), c("NestedArray", "R6"))
  expect_equal(dim(sub$as.array()), 10, 1)
})
```

**Comment by keller-mark** [comment]
I had meant using the string literal `":"` in the selection list to achieve the equivalent behavior of Numpy like 

```
a = np.zeros((4,5,6))
b = a[1:2,:,0:3]
```
Where the middle `:` without a start or end selects all 5 items along the middle axis.

This would be in contrast to the behavior of the string `"..."` which we use to select along all of the remaining array dimensions.

**Comment by dblodgett-usgs** [comment]
I see -- I knew I was missing something. My Python isn't super strong. I'm working through a few things related to this and will see if I can write up some testing.

**Comment by keller-mark** [comment]
Fixed in https://github.com/keller-mark/pizzarr/pull/85
