### ISSUE TITLE
Test with step > 1

### ISSUE THREAD

**Issue by keller-mark** [keller-mark/pizzarr#42]

**Comment by dblodgett-usgs** [comment]
I spent a chunk of time tracing through the code and think I found how to handle this -- please review here: https://github.com/dblodgett-usgs/pizzarr/commit/cd9813d5afaa09555d1d2dfb6f9909ef4f8c7e82#diff-ed8388e7a7b71e8a13ae09506816fc3ecb17d36feafdbc6ee0c99d6459db51d4L28

**Comment by keller-mark** [comment]
Fixed in #85 and #90
