### ISSUE TITLE
Support for integer indexing

### ISSUE THREAD

**Issue by keller-mark** [keller-mark/pizzarr#43]
Also: support zero-based integer indexing with a `zb_int()` function (analogous to `zb_slice()`)

**Comment by Artur-man** [comment]
Are these the intended functions and classes for the `zb_int`: [int.R](https://github.com/Artur-man/pizzarr/blob/main/R/int.R)

https://github.com/Artur-man/pizzarr/blob/3d3231ca79c3c29a44664ea75f747513e35dcc33/R/int.R#L3-L30

**Comment by Artur-man** [comment]
There is also the `IntArrayDimIndexer`:

https://github.com/zarr-developers/zarr-python/blob/5dd4a0e6cdc04c6413e14f57f61d389972ea937c/zarr/indexing.py#L457-L468
