### ISSUE TITLE
Interest in rebooting development on this?

### ISSUE THREAD

**Issue by dblodgett-usgs** [keller-mark/pizzarr#9]
**User story**

As an R developer working with NetCDF data stored in ZARR, I need a low level interface to layer NetCDF metadata interpretation code from https://hypertidy.github.io/ncmeta/ and similar packages such as https://github.com/DOI-USGS/ncdfgeom and https://github.com/r-spatial/stars

**Preferred solution**

A group of motivated users pushes this package across the finish line and wraps it in an API that can be called with nearly the same function signatures as the https://github.com/mjwoods/RNetCDF package. 

Seems like there's a solid start here. @keller-mark -- do you think you have any space to reboot work on this? I could make some contributions and maybe twist some arms from around the community to do the same.

**Comment by keller-mark** [comment]
Hi @dblodgett-usgs 

If you have not seen Rarr you should check out https://github.com/grimbough/Rarr as it seems to be further along than this implementation.

Regardless, I will try to find time to work on this again if for nothing else than to experiment with the possibility of a more R-based implementation. I also tried to reflect the zarr-python API here which could be another differentiator.

**Comment by dblodgett-usgs** [comment]
Thanks for the pointer -- that's interesting. 

I'm new to R6 and really come to this from the landscape / climate data domain. 

I see a comment over at Rarr in an issue calling for a C++ ZARR implementation that could be wrapped in an R package. I also see the logic in what they've done with Rarr -- just focusing on a core (non hierarchical) array. That seems sensible but I still think it's important to get ZARR going in base R in a complete way. 

Given that, I'd love to find time to support what you are doing here. Are you interested in taking PRs? I know that can just cause more work and headaches given that others are going to have slightly different coding style and such.

Cheers!

**Comment by keller-mark** [comment]
Hi @dblodgett-usgs 

Happy to accept PRs - I just merged #10 but I am going to take another break - more things work now but one new test is not passing https://github.com/keller-mark/pizzarr/blob/1536a48728134769c39e3c0e47795e4cc891fc56/tests/testthat/test-get.R#L111 - it is related to 0- vs 1- based indexing differences.

I think it makes more sense to use 0-based indexing for the array slicing to match the zarr implementations in other languages, but now I am running into the issue that I want to use R-like / 1-based indexing to access the corresponding values internally like at https://github.com/keller-mark/pizzarr/blob/1536a48728134769c39e3c0e47795e4cc891fc56/R/array-nested.R#L219 - I want to keep the 1-based indexing scoped to the NestedArray class, just need to figure out how best to do that in practice as there are some edge cases like the zero-dimensional array etc.

**Comment by dblodgett-usgs** [comment]
It's been awesome to see this start moving again! I am trying to arrange some time for me to contribute some time to this over the winter. 🙏 for all your work!!!

**Comment by keller-mark** [comment]
Sounds great! It should be more straightforward to contribute now that a few things are at least functional!
